### ISSUE TITLE
error when create paste through api with curl

### ISSUE THREAD

**Issue by wzdnzd** [Ale32bit/DevBin#44]
Always return a 500 status code when i call the api with curl but it works well in swagger, what should i do? It would be appreciated that if you can help me.

error messages:
![error messages](https://s2.loli.net/2022/09/02/iIEbsGWLfj8Q9Fm.png)

**Comment by Ale32bit** [comment]
Hi, can you provide the request payload you used to trigger the error?

I believe it could have been caused by a bug in the syntaxName check, which is fixed in 62ad4054431f04abc3c9454f8c5a73ae7b99dfeb, but the release has yet to be updated with it.

You should try to reproduce the bug from https://beta.devbin.dev.

**Comment by wzdnzd** [comment]
Thanks for your reply, the problem still exists when I try to call the beta api. But I found that it works fine after adding the cookie in the header.

**Comment by Ale32bit** [comment]
You should use beta.devbin.dev temporarily until it is released.

**Comment by wzdnzd** [comment]
Thanks a lot.
